# Generated by Django 4.2.10 on 2024-03-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Plants", "0003_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="created_at", new_name="Created_at",
        ),
        migrations.AddField(
            model_name="cart",
            name="length",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
