# Generated by Django 4.2.10 on 2024-03-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Plants", "0004_rename_created_at_cart_created_at_cart_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="image",
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
