# Generated by Django 4.2.10 on 2024-03-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ItemDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("length", models.FloatField()),
                ("qty", models.IntegerField()),
                ("tax", models.FloatField()),
                ("image", models.CharField(max_length=150)),
                ("total", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "itemsid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Plants.items",
                    ),
                ),
            ],
        ),
    ]
